### ISSUE TITLE
can't clone your own repo: KeyError: 'parent'

### ISSUE THREAD

**Issue by jwilk** [sociomantic/git-hub#141]
I wanted to clone my own repo, but it didn't work:
```
$ git hub clone jwilk/didjvu
Forking jwilk/didjvu to jwilk/didjvu
Cloning git@github.com:jwilk/didjvu.git to didjvu
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 2002, in <module>
    main()
  File "/usr/bin/git-hub", line 1996, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 614, in check_config_and_run
    cmd.run(parser, args)
  File "/usr/bin/git-hub", line 798, in run
    remote_url = repo['parent'][config.urltype]
KeyError: 'parent'
```

**Comment by jwilk** [comment]
Duplicate of #43. Sorry!
