### ISSUE TITLE
clone: NameError: global name 'proj' is not defined

### ISSUE THREAD

**Issue by jwilk** [sociomantic/git-hub#168]
It looks like 340ef5665156 completely broke cloning:
```
$ git hub clone sociomantic/git-hub
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 2017, in <module>
    main()
  File "/usr/bin/git-hub", line 2011, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 615, in check_config_and_run
    cmd.run(parser, args)
  File "/usr/bin/git-hub", line 769, in run
    '{}/{}'.format(owner, proj))
  File "/usr/bin/git-hub", line 814, in set_not_own_repo_params
    if repo['name'] == proj and repo['fork']:
NameError: global name 'proj' is not defined
```

**Comment by leandro-lucarella-sociomantic** [comment]
Yup, and #149 should fix it. And yes, we need to add testing to this... :-/

**Comment by leandro-lucarella-sociomantic** [comment]
#148 merged
